baseurl = "https://tranduythanh.github.io/"
title = "From zero to AI"
author = "Trần Duy Thanh"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"

pygmentsstyle       = "monokai"
pygmentscodefences  = true

[params]
  sitename = "From Zero to AI"

[[menu.main]]
    name = "About"
    url  = "/"
[[menu.main]]
    name = "Home"
    url  = "/"
[[menu.main]]
    name = "Resume"
    url  = "/"
